// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

pub const CAPABILITY_ID: &str = "lenso.message.sms@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const SMS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SMS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const SEND_OPERATION: &str = "send";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SendRequest {
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: String,
    #[serde(rename = "destination")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub destination: String,
}

impl fmt::Debug for SendRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SendRequest")
            .field("body", &"<redacted>")
            .field("destination", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SendResponse {
    #[serde(rename = "accepted")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SendError {
    InvalidDestination,
    Rejected,
    Throttled,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Sms;
impl RequestCapability for Sms {
    type Request = SendRequest;
    type Response = SendResponse;
    type DomainError = SendError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SEND_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SmsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).send(context, request)
    }
}

impl serde::Serialize for SendError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidDestination => serializer.serialize_str("invalid_destination"),
            Self::Rejected => serializer.serialize_str("rejected"),
            Self::Throttled => serializer.serialize_str("throttled"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SendError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_destination" => Ok(Self::InvalidDestination),
                "rejected" => Ok(Self::Rejected),
                "throttled" => Ok(Self::Throttled),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_send_request(value: &SendRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_send_request(wire: &str) -> Result<SendRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_send_response(value: &SendResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_send_response(wire: &str) -> Result<SendResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_send_error(value: &SendError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_send_error(wire: &str) -> Result<SendError, serde_json::Error> { decode_portable_json(wire) }

pub trait SmsProvider: fmt::Debug + 'static {
    fn send(&self, context: InvocationContext, request: SendRequest) -> NativeRequestFuture<Sms>;
}

#[derive(Debug)]
struct SmsRequestEndpoint { provider: Rc<dyn SmsProvider> }

#[derive(Debug)]
pub struct SmsEndpoint<P: SmsProvider> { provider: Rc<P>, request_endpoint: SmsRequestEndpoint }
impl<P: SmsProvider> SmsEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SmsProvider> = provider.clone();
        Self { provider, request_endpoint: SmsRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SmsProvider> NativeRequestEndpoint for SmsEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SEND_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SEND_OPERATION => {
                let Ok(request) = request.downcast::<SendRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).send(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct SmsClient {
    send: NativeRequestHandle<Sms>,
}
impl SmsClient {
    pub fn new(handle: NativeRequestHandle<Sms>) -> Self {
        Self { send: handle }
    }

    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            send: dependencies.one::<Sms>()?,
        })
    }

    pub async fn send(&self, request: SendRequest) -> Result<SendResponse, SmsInvocationError> {
        self.send.invoke(SEND_OPERATION, request).await
            .map_err(SmsInvocationError::Runtime)?
            .map_err(SmsInvocationError::Domain)
    }

    pub async fn send_with_context(&self, context: InvocationContext, request: SendRequest) -> Result<SendResponse, SmsInvocationError> {
        self.send.invoke_with_context(SEND_OPERATION, context, request).await
            .map_err(SmsInvocationError::Runtime)?
            .map_err(SmsInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SmsInvocationError {
    Domain(SendError),
    Runtime(RuntimeFailure),
}
