[package]
name = "lenso-capability-auth"
version = "0.1.1"
edition.workspace = true
license.workspace = true
publish = true
repository.workspace = true
description = "Generated Auth Capability contracts for Lenso vNext."
build = "build.rs"

[dependencies]
futures.workspace = true
lenso-contract-runtime = "0.1.0"
lenso-kernel = "0.1.4"
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
lenso-contract-codegen = "0.5.2"

[lints]
workspace = true
