[package]
name = "lenso-auth-anonymous-module"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
[package.metadata.lenso]
package-id = "lenso.auth.anonymous"

[dependencies]
lenso = { git = "https://github.com/LioRael/lenso-runtime-rust.git", rev = "48cf37b6475a0dbbe4ad8492888ed7c6c17abae4" }
base64.workspace = true
futures.workspace = true
getrandom.workspace = true
lenso-capability-anonymous-auth = { path = "../lenso-capability-anonymous-auth" }
lenso-capability-credential-issuer = { path = "../lenso-capability-credential-issuer" }
lenso-capability-identity-directory = { path = "../lenso-capability-identity-directory" }
lenso-kernel = "0.1.9"
lenso-native-adapter = { git = "https://github.com/LioRael/lenso-runtime-rust.git", rev = "48cf37b6475a0dbbe4ad8492888ed7c6c17abae4" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true
[lints]
workspace = true
