// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

pub const CAPABILITY_ID: &str = "lenso.identity.directory@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const DIRECTORY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const DIRECTORY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const ENSURE_IDENTITY_OPERATION: &str = "ensure_identity";
pub const READ_STATUS_OPERATION: &str = "read_status";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnsureIdentityRequest {
    #[serde(rename = "external_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub external_subject: String,
    #[serde(rename = "provider")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnsureIdentityResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EnsureIdentityError {
    Disabled,
    InvalidIdentity,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadStatusRequest {
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadStatusResponse {
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ReadStatusResponseStatus,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReadStatusResponseStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "disabled")]
    Disabled,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadStatusError {
    InvalidSubject,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct DirectoryEnsureIdentity;
impl RequestCapability for DirectoryEnsureIdentity {
    type Request = EnsureIdentityRequest;
    type Response = EnsureIdentityResponse;
    type DomainError = EnsureIdentityError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ENSURE_IDENTITY_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).ensure_identity(context, request)
    }
}

#[derive(Debug)]
pub struct DirectoryReadStatus;
impl RequestCapability for DirectoryReadStatus {
    type Request = ReadStatusRequest;
    type Response = ReadStatusResponse;
    type DomainError = ReadStatusError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_STATUS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DirectoryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_status(context, request)
    }
}

impl serde::Serialize for EnsureIdentityError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::InvalidIdentity => serializer.serialize_str("invalid_identity"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for EnsureIdentityError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "invalid_identity" => Ok(Self::InvalidIdentity),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadStatusError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidSubject => serializer.serialize_str("invalid_subject"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadStatusError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_subject" => Ok(Self::InvalidSubject),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_ensure_identity_request(value: &EnsureIdentityRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ensure_identity_request(wire: &str) -> Result<EnsureIdentityRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_ensure_identity_response(value: &EnsureIdentityResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ensure_identity_response(wire: &str) -> Result<EnsureIdentityResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_ensure_identity_error(value: &EnsureIdentityError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ensure_identity_error(wire: &str) -> Result<EnsureIdentityError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_status_request(value: &ReadStatusRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_status_request(wire: &str) -> Result<ReadStatusRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_status_response(value: &ReadStatusResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_status_response(wire: &str) -> Result<ReadStatusResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_status_error(value: &ReadStatusError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_status_error(wire: &str) -> Result<ReadStatusError, serde_json::Error> { decode_portable_json(wire) }

pub trait DirectoryProvider: fmt::Debug + 'static {
    fn ensure_identity(&self, context: InvocationContext, request: EnsureIdentityRequest) -> NativeRequestFuture<DirectoryEnsureIdentity>;
    fn read_status(&self, context: InvocationContext, request: ReadStatusRequest) -> NativeRequestFuture<DirectoryReadStatus>;
}

#[derive(Debug)]
struct DirectoryRequestEndpoint { provider: Rc<dyn DirectoryProvider> }

#[derive(Debug)]
pub struct DirectoryEndpoint<P: DirectoryProvider> { provider: Rc<P>, request_endpoint: DirectoryRequestEndpoint }
impl<P: DirectoryProvider> DirectoryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn DirectoryProvider> = provider.clone();
        Self { provider, request_endpoint: DirectoryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: DirectoryProvider> NativeRequestEndpoint for DirectoryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ENSURE_IDENTITY_OPERATION,
        READ_STATUS_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ENSURE_IDENTITY_OPERATION => {
                let Ok(request) = request.downcast::<EnsureIdentityRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).ensure_identity(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_STATUS_OPERATION => {
                let Ok(request) = request.downcast::<ReadStatusRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_status(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct DirectoryClient {
    ensure_identity: NativeRequestHandle<DirectoryEnsureIdentity>,
    read_status: NativeRequestHandle<DirectoryReadStatus>,
}
impl DirectoryClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            ensure_identity: dependencies.one::<DirectoryEnsureIdentity>()?,
            read_status: dependencies.one::<DirectoryReadStatus>()?,
        })
    }

    pub async fn ensure_identity(&self, request: EnsureIdentityRequest) -> Result<EnsureIdentityResponse, DirectoryEnsureIdentityInvocationError> {
        self.ensure_identity.invoke(ENSURE_IDENTITY_OPERATION, request).await
            .map_err(DirectoryEnsureIdentityInvocationError::Runtime)?
            .map_err(DirectoryEnsureIdentityInvocationError::Domain)
    }

    pub async fn ensure_identity_with_context(&self, context: InvocationContext, request: EnsureIdentityRequest) -> Result<EnsureIdentityResponse, DirectoryEnsureIdentityInvocationError> {
        self.ensure_identity.invoke_with_context(ENSURE_IDENTITY_OPERATION, context, request).await
            .map_err(DirectoryEnsureIdentityInvocationError::Runtime)?
            .map_err(DirectoryEnsureIdentityInvocationError::Domain)
    }

    pub async fn read_status(&self, request: ReadStatusRequest) -> Result<ReadStatusResponse, DirectoryReadStatusInvocationError> {
        self.read_status.invoke(READ_STATUS_OPERATION, request).await
            .map_err(DirectoryReadStatusInvocationError::Runtime)?
            .map_err(DirectoryReadStatusInvocationError::Domain)
    }

    pub async fn read_status_with_context(&self, context: InvocationContext, request: ReadStatusRequest) -> Result<ReadStatusResponse, DirectoryReadStatusInvocationError> {
        self.read_status.invoke_with_context(READ_STATUS_OPERATION, context, request).await
            .map_err(DirectoryReadStatusInvocationError::Runtime)?
            .map_err(DirectoryReadStatusInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum DirectoryEnsureIdentityInvocationError {
    Domain(EnsureIdentityError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum DirectoryReadStatusInvocationError {
    Domain(ReadStatusError),
    Runtime(RuntimeFailure),
}
