// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

pub const CAPABILITY_ID: &str = "lenso.auth.password@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const PASSWORD_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PASSWORD_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const LOGIN_OPERATION: &str = "login";
pub const REGISTER_OPERATION: &str = "register";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoginRequest {
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "password")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub password: String,
}

impl fmt::Debug for LoginRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("LoginRequest")
            .field("identifier", &self.identifier)
            .field("password", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct LoginResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for LoginResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("LoginResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum LoginError {
    Disabled,
    InvalidCredentials,
    InvalidIdentifier,
    RateLimited,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RegisterRequest {
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "password")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub password: String,
}

impl fmt::Debug for RegisterRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RegisterRequest")
            .field("identifier", &self.identifier)
            .field("password", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RegisterResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for RegisterResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RegisterResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum RegisterError {
    Disabled,
    IdentifierTaken,
    InvalidIdentifier,
    WeakPassword,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct PasswordLogin;
impl RequestCapability for PasswordLogin {
    type Request = LoginRequest;
    type Response = LoginResponse;
    type DomainError = LoginError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LOGIN_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasswordRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).login(context, request)
    }
}

#[derive(Debug)]
pub struct PasswordRegister;
impl RequestCapability for PasswordRegister {
    type Request = RegisterRequest;
    type Response = RegisterResponse;
    type DomainError = RegisterError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REGISTER_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PasswordRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).register(context, request)
    }
}

impl serde::Serialize for LoginError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::InvalidCredentials => serializer.serialize_str("invalid_credentials"),
            Self::InvalidIdentifier => serializer.serialize_str("invalid_identifier"),
            Self::RateLimited => serializer.serialize_str("rate_limited"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for LoginError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "invalid_credentials" => Ok(Self::InvalidCredentials),
                "invalid_identifier" => Ok(Self::InvalidIdentifier),
                "rate_limited" => Ok(Self::RateLimited),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RegisterError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::IdentifierTaken => serializer.serialize_str("identifier_taken"),
            Self::InvalidIdentifier => serializer.serialize_str("invalid_identifier"),
            Self::WeakPassword => serializer.serialize_str("weak_password"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RegisterError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "identifier_taken" => Ok(Self::IdentifierTaken),
                "invalid_identifier" => Ok(Self::InvalidIdentifier),
                "weak_password" => Ok(Self::WeakPassword),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_login_request(value: &LoginRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_login_request(wire: &str) -> Result<LoginRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_login_response(value: &LoginResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_login_response(wire: &str) -> Result<LoginResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_login_error(value: &LoginError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_login_error(wire: &str) -> Result<LoginError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_register_request(value: &RegisterRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_register_request(wire: &str) -> Result<RegisterRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_register_response(value: &RegisterResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_register_response(wire: &str) -> Result<RegisterResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_register_error(value: &RegisterError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_register_error(wire: &str) -> Result<RegisterError, serde_json::Error> { decode_portable_json(wire) }

pub trait PasswordProvider: fmt::Debug + 'static {
    fn login(&self, context: InvocationContext, request: LoginRequest) -> NativeRequestFuture<PasswordLogin>;
    fn register(&self, context: InvocationContext, request: RegisterRequest) -> NativeRequestFuture<PasswordRegister>;
}

#[derive(Debug)]
struct PasswordRequestEndpoint { provider: Rc<dyn PasswordProvider> }

#[derive(Debug)]
pub struct PasswordEndpoint<P: PasswordProvider> { provider: Rc<P>, request_endpoint: PasswordRequestEndpoint }
impl<P: PasswordProvider> PasswordEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn PasswordProvider> = provider.clone();
        Self { provider, request_endpoint: PasswordRequestEndpoint { provider: request_provider } }
    }
}

impl<P: PasswordProvider> NativeRequestEndpoint for PasswordEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        LOGIN_OPERATION,
        REGISTER_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            LOGIN_OPERATION => {
                let Ok(request) = request.downcast::<LoginRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).login(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REGISTER_OPERATION => {
                let Ok(request) = request.downcast::<RegisterRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).register(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct PasswordClient {
    login: NativeRequestHandle<PasswordLogin>,
    register: NativeRequestHandle<PasswordRegister>,
}
impl PasswordClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            login: dependencies.one::<PasswordLogin>()?,
            register: dependencies.one::<PasswordRegister>()?,
        })
    }

    pub async fn login(&self, request: LoginRequest) -> Result<LoginResponse, PasswordLoginInvocationError> {
        self.login.invoke(LOGIN_OPERATION, request).await
            .map_err(PasswordLoginInvocationError::Runtime)?
            .map_err(PasswordLoginInvocationError::Domain)
    }

    pub async fn login_with_context(&self, context: InvocationContext, request: LoginRequest) -> Result<LoginResponse, PasswordLoginInvocationError> {
        self.login.invoke_with_context(LOGIN_OPERATION, context, request).await
            .map_err(PasswordLoginInvocationError::Runtime)?
            .map_err(PasswordLoginInvocationError::Domain)
    }

    pub async fn register(&self, request: RegisterRequest) -> Result<RegisterResponse, PasswordRegisterInvocationError> {
        self.register.invoke(REGISTER_OPERATION, request).await
            .map_err(PasswordRegisterInvocationError::Runtime)?
            .map_err(PasswordRegisterInvocationError::Domain)
    }

    pub async fn register_with_context(&self, context: InvocationContext, request: RegisterRequest) -> Result<RegisterResponse, PasswordRegisterInvocationError> {
        self.register.invoke_with_context(REGISTER_OPERATION, context, request).await
            .map_err(PasswordRegisterInvocationError::Runtime)?
            .map_err(PasswordRegisterInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PasswordLoginInvocationError {
    Domain(LoginError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PasswordRegisterInvocationError {
    Domain(RegisterError),
    Runtime(RuntimeFailure),
}
