// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

pub const CAPABILITY_ID: &str = "lenso.auth.phone@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const PHONE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PHONE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

pub const PASSWORD_LOGIN_OPERATION: &str = "password_login";
pub const SET_PASSWORD_OPERATION: &str = "set_password";
pub const START_OTP_OPERATION: &str = "start_otp";
pub const VERIFY_OTP_OPERATION: &str = "verify_otp";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PasswordLoginRequest {
    #[serde(rename = "device_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub device_id: Option<String>,
    #[serde(rename = "password")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub password: String,
    #[serde(rename = "phone")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub phone: String,
}

impl fmt::Debug for PasswordLoginRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PasswordLoginRequest")
            .field("device_id", &self.device_id)
            .field("password", &"<redacted>")
            .field("phone", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PasswordLoginResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "masked_phone")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub masked_phone: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for PasswordLoginResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PasswordLoginResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("masked_phone", &self.masked_phone)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PasswordLoginError {
    Disabled,
    InvalidCredentials,
    InvalidPhone,
    RateLimited,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetPasswordRequest {
    #[serde(rename = "password")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub password: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for SetPasswordRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SetPasswordRequest")
            .field("password", &"<redacted>")
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetPasswordResponse {
    #[serde(rename = "updated")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SetPasswordError {
    Disabled,
    Forbidden,
    InvalidSubject,
    NotFound,
    WeakPassword,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StartOtpRequest {
    #[serde(rename = "client_ip")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub client_ip: Option<String>,
    #[serde(rename = "phone")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub phone: String,
    #[serde(rename = "purpose")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub purpose: StartOtpRequestPurpose,
}

impl fmt::Debug for StartOtpRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("StartOtpRequest")
            .field("client_ip", &self.client_ip)
            .field("phone", &"<redacted>")
            .field("purpose", &self.purpose)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum StartOtpRequestPurpose {
    #[serde(rename = "login")]
    Login,
    #[serde(rename = "register")]
    Register,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StartOtpResponse {
    #[serde(rename = "challenge_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub challenge_id: String,
    #[serde(rename = "debug_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub debug_code: Option<String>,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "resend_after")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resend_after: Timestamp,
}

impl fmt::Debug for StartOtpResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("StartOtpResponse")
            .field("challenge_id", &self.challenge_id)
            .field("debug_code", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("resend_after", &self.resend_after)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum StartOtpError {
    DeliveryRejected,
    InvalidPhone,
    InvalidPurpose,
    RateLimited,
    ResendTooSoon,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VerifyOtpRequest {
    #[serde(rename = "challenge_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub challenge_id: String,
    #[serde(rename = "code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code: String,
    #[serde(rename = "device_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub device_id: Option<String>,
}

impl fmt::Debug for VerifyOtpRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("VerifyOtpRequest")
            .field("challenge_id", &self.challenge_id)
            .field("code", &"<redacted>")
            .field("device_id", &self.device_id)
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct VerifyOtpResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "masked_phone")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub masked_phone: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for VerifyOtpResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("VerifyOtpResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("masked_phone", &self.masked_phone)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum VerifyOtpError {
    Disabled,
    Expired,
    InvalidChallenge,
    InvalidCode,
    TooManyAttempts,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct PhonePasswordLogin;
impl RequestCapability for PhonePasswordLogin {
    type Request = PasswordLoginRequest;
    type Response = PasswordLoginResponse;
    type DomainError = PasswordLoginError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PASSWORD_LOGIN_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PhoneRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).password_login(context, request)
    }
}

#[derive(Debug)]
pub struct PhoneSetPassword;
impl RequestCapability for PhoneSetPassword {
    type Request = SetPasswordRequest;
    type Response = SetPasswordResponse;
    type DomainError = SetPasswordError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SET_PASSWORD_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PhoneRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).set_password(context, request)
    }
}

#[derive(Debug)]
pub struct PhoneStartOtp;
impl RequestCapability for PhoneStartOtp {
    type Request = StartOtpRequest;
    type Response = StartOtpResponse;
    type DomainError = StartOtpError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != START_OTP_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PhoneRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).start_otp(context, request)
    }
}

#[derive(Debug)]
pub struct PhoneVerifyOtp;
impl RequestCapability for PhoneVerifyOtp {
    type Request = VerifyOtpRequest;
    type Response = VerifyOtpResponse;
    type DomainError = VerifyOtpError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != VERIFY_OTP_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PhoneRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).verify_otp(context, request)
    }
}

impl serde::Serialize for PasswordLoginError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::InvalidCredentials => serializer.serialize_str("invalid_credentials"),
            Self::InvalidPhone => serializer.serialize_str("invalid_phone"),
            Self::RateLimited => serializer.serialize_str("rate_limited"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PasswordLoginError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "invalid_credentials" => Ok(Self::InvalidCredentials),
                "invalid_phone" => Ok(Self::InvalidPhone),
                "rate_limited" => Ok(Self::RateLimited),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for SetPasswordError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidSubject => serializer.serialize_str("invalid_subject"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::WeakPassword => serializer.serialize_str("weak_password"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SetPasswordError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_subject" => Ok(Self::InvalidSubject),
                "not_found" => Ok(Self::NotFound),
                "weak_password" => Ok(Self::WeakPassword),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for StartOtpError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::DeliveryRejected => serializer.serialize_str("delivery_rejected"),
            Self::InvalidPhone => serializer.serialize_str("invalid_phone"),
            Self::InvalidPurpose => serializer.serialize_str("invalid_purpose"),
            Self::RateLimited => serializer.serialize_str("rate_limited"),
            Self::ResendTooSoon => serializer.serialize_str("resend_too_soon"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for StartOtpError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "delivery_rejected" => Ok(Self::DeliveryRejected),
                "invalid_phone" => Ok(Self::InvalidPhone),
                "invalid_purpose" => Ok(Self::InvalidPurpose),
                "rate_limited" => Ok(Self::RateLimited),
                "resend_too_soon" => Ok(Self::ResendTooSoon),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for VerifyOtpError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Expired => serializer.serialize_str("expired"),
            Self::InvalidChallenge => serializer.serialize_str("invalid_challenge"),
            Self::InvalidCode => serializer.serialize_str("invalid_code"),
            Self::TooManyAttempts => serializer.serialize_str("too_many_attempts"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for VerifyOtpError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "expired" => Ok(Self::Expired),
                "invalid_challenge" => Ok(Self::InvalidChallenge),
                "invalid_code" => Ok(Self::InvalidCode),
                "too_many_attempts" => Ok(Self::TooManyAttempts),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_password_login_request(value: &PasswordLoginRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_password_login_request(wire: &str) -> Result<PasswordLoginRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_password_login_response(value: &PasswordLoginResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_password_login_response(wire: &str) -> Result<PasswordLoginResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_password_login_error(value: &PasswordLoginError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_password_login_error(wire: &str) -> Result<PasswordLoginError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_set_password_request(value: &SetPasswordRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_password_request(wire: &str) -> Result<SetPasswordRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_set_password_response(value: &SetPasswordResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_password_response(wire: &str) -> Result<SetPasswordResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_set_password_error(value: &SetPasswordError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_password_error(wire: &str) -> Result<SetPasswordError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_start_otp_request(value: &StartOtpRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_otp_request(wire: &str) -> Result<StartOtpRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_start_otp_response(value: &StartOtpResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_otp_response(wire: &str) -> Result<StartOtpResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_start_otp_error(value: &StartOtpError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_otp_error(wire: &str) -> Result<StartOtpError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_verify_otp_request(value: &VerifyOtpRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_verify_otp_request(wire: &str) -> Result<VerifyOtpRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_verify_otp_response(value: &VerifyOtpResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_verify_otp_response(wire: &str) -> Result<VerifyOtpResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_verify_otp_error(value: &VerifyOtpError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_verify_otp_error(wire: &str) -> Result<VerifyOtpError, serde_json::Error> { decode_portable_json(wire) }

pub trait PhoneProvider: fmt::Debug + 'static {
    fn password_login(&self, context: InvocationContext, request: PasswordLoginRequest) -> NativeRequestFuture<PhonePasswordLogin>;
    fn set_password(&self, context: InvocationContext, request: SetPasswordRequest) -> NativeRequestFuture<PhoneSetPassword>;
    fn start_otp(&self, context: InvocationContext, request: StartOtpRequest) -> NativeRequestFuture<PhoneStartOtp>;
    fn verify_otp(&self, context: InvocationContext, request: VerifyOtpRequest) -> NativeRequestFuture<PhoneVerifyOtp>;
}

#[derive(Debug)]
struct PhoneRequestEndpoint { provider: Rc<dyn PhoneProvider> }

#[derive(Debug)]
pub struct PhoneEndpoint<P: PhoneProvider> { provider: Rc<P>, request_endpoint: PhoneRequestEndpoint }
impl<P: PhoneProvider> PhoneEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn PhoneProvider> = provider.clone();
        Self { provider, request_endpoint: PhoneRequestEndpoint { provider: request_provider } }
    }
}

impl<P: PhoneProvider> NativeRequestEndpoint for PhoneEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        PASSWORD_LOGIN_OPERATION,
        SET_PASSWORD_OPERATION,
        START_OTP_OPERATION,
        VERIFY_OTP_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            PASSWORD_LOGIN_OPERATION => {
                let Ok(request) = request.downcast::<PasswordLoginRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).password_login(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            SET_PASSWORD_OPERATION => {
                let Ok(request) = request.downcast::<SetPasswordRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).set_password(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            START_OTP_OPERATION => {
                let Ok(request) = request.downcast::<StartOtpRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).start_otp(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            VERIFY_OTP_OPERATION => {
                let Ok(request) = request.downcast::<VerifyOtpRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).verify_otp(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[derive(Debug)]
pub struct PhoneClient {
    password_login: NativeRequestHandle<PhonePasswordLogin>,
    set_password: NativeRequestHandle<PhoneSetPassword>,
    start_otp: NativeRequestHandle<PhoneStartOtp>,
    verify_otp: NativeRequestHandle<PhoneVerifyOtp>,
}
impl PhoneClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            password_login: dependencies.one::<PhonePasswordLogin>()?,
            set_password: dependencies.one::<PhoneSetPassword>()?,
            start_otp: dependencies.one::<PhoneStartOtp>()?,
            verify_otp: dependencies.one::<PhoneVerifyOtp>()?,
        })
    }

    pub async fn password_login(&self, request: PasswordLoginRequest) -> Result<PasswordLoginResponse, PhonePasswordLoginInvocationError> {
        self.password_login.invoke(PASSWORD_LOGIN_OPERATION, request).await
            .map_err(PhonePasswordLoginInvocationError::Runtime)?
            .map_err(PhonePasswordLoginInvocationError::Domain)
    }

    pub async fn password_login_with_context(&self, context: InvocationContext, request: PasswordLoginRequest) -> Result<PasswordLoginResponse, PhonePasswordLoginInvocationError> {
        self.password_login.invoke_with_context(PASSWORD_LOGIN_OPERATION, context, request).await
            .map_err(PhonePasswordLoginInvocationError::Runtime)?
            .map_err(PhonePasswordLoginInvocationError::Domain)
    }

    pub async fn set_password(&self, request: SetPasswordRequest) -> Result<SetPasswordResponse, PhoneSetPasswordInvocationError> {
        self.set_password.invoke(SET_PASSWORD_OPERATION, request).await
            .map_err(PhoneSetPasswordInvocationError::Runtime)?
            .map_err(PhoneSetPasswordInvocationError::Domain)
    }

    pub async fn set_password_with_context(&self, context: InvocationContext, request: SetPasswordRequest) -> Result<SetPasswordResponse, PhoneSetPasswordInvocationError> {
        self.set_password.invoke_with_context(SET_PASSWORD_OPERATION, context, request).await
            .map_err(PhoneSetPasswordInvocationError::Runtime)?
            .map_err(PhoneSetPasswordInvocationError::Domain)
    }

    pub async fn start_otp(&self, request: StartOtpRequest) -> Result<StartOtpResponse, PhoneStartOtpInvocationError> {
        self.start_otp.invoke(START_OTP_OPERATION, request).await
            .map_err(PhoneStartOtpInvocationError::Runtime)?
            .map_err(PhoneStartOtpInvocationError::Domain)
    }

    pub async fn start_otp_with_context(&self, context: InvocationContext, request: StartOtpRequest) -> Result<StartOtpResponse, PhoneStartOtpInvocationError> {
        self.start_otp.invoke_with_context(START_OTP_OPERATION, context, request).await
            .map_err(PhoneStartOtpInvocationError::Runtime)?
            .map_err(PhoneStartOtpInvocationError::Domain)
    }

    pub async fn verify_otp(&self, request: VerifyOtpRequest) -> Result<VerifyOtpResponse, PhoneVerifyOtpInvocationError> {
        self.verify_otp.invoke(VERIFY_OTP_OPERATION, request).await
            .map_err(PhoneVerifyOtpInvocationError::Runtime)?
            .map_err(PhoneVerifyOtpInvocationError::Domain)
    }

    pub async fn verify_otp_with_context(&self, context: InvocationContext, request: VerifyOtpRequest) -> Result<VerifyOtpResponse, PhoneVerifyOtpInvocationError> {
        self.verify_otp.invoke_with_context(VERIFY_OTP_OPERATION, context, request).await
            .map_err(PhoneVerifyOtpInvocationError::Runtime)?
            .map_err(PhoneVerifyOtpInvocationError::Domain)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PhonePasswordLoginInvocationError {
    Domain(PasswordLoginError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PhoneSetPasswordInvocationError {
    Domain(SetPasswordError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PhoneStartOtpInvocationError {
    Domain(StartOtpError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PhoneVerifyOtpInvocationError {
    Domain(VerifyOtpError),
    Runtime(RuntimeFailure),
}
