[package]
name = "lenso-capability-anonymous-auth"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true

[dependencies]
schemars = "1.2"
lenso-module-authoring = { version = "0.1.0", git = "https://github.com/LioRael/lenso-protocols", rev = "c1f1dce2cf93420f924d37074035f170e4153fc5" }
lenso-contract-authoring = { version = "0.1.0", git = "https://github.com/LioRael/lenso-protocols", rev = "c1f1dce2cf93420f924d37074035f170e4153fc5" }
futures.workspace = true
lenso-contract-runtime = "0.1.0"
lenso-kernel = "0.1.9"
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
lenso-contract-authoring = { version = "0.1.0", git = "https://github.com/LioRael/lenso-protocols", rev = "c1f1dce2cf93420f924d37074035f170e4153fc5" }
lenso-contract-codegen = { version = "0.6.1", git = "https://github.com/LioRael/lenso-protocols", rev = "c1f1dce2cf93420f924d37074035f170e4153fc5" }
schemars = "1.2"
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
