// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

use lenso_module_authoring::CapabilityClient;
pub const CAPABILITY_ID: &str = "lenso.auth.federated@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const FEDERATED_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const FEDERATED_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_federated { () => { "{\"capability_id\":\"lenso.auth.federated@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"complete\",\"start\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_federated_client { () => { "{\"capability_id\":\"lenso.auth.federated@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

pub const COMPLETE_OPERATION: &str = "complete";
pub const START_OPERATION: &str = "start";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteRequest {
    #[serde(rename = "code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub code: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: String,
}

impl fmt::Debug for CompleteRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CompleteRequest")
            .field("code", &"<redacted>")
            .field("state", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "provider")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider: String,
    #[serde(rename = "return_to")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub return_to: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

impl fmt::Debug for CompleteResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CompleteResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("provider", &self.provider)
            .field("return_to", &self.return_to)
            .field("session_id", &self.session_id)
            .field("subject", &self.subject)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompleteError {
    Disabled,
    InvalidCallback,
    InvalidState,
    ProviderRejected,
    UnverifiedIdentity,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StartRequest {
    #[serde(rename = "return_to")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub return_to: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StartResponse {
    #[serde(rename = "authorization_url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub authorization_url: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "provider")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum StartError {
    InvalidReturnTo,
    ProviderUnavailable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct FederatedComplete;
impl RequestCapability for FederatedComplete {
    type Request = CompleteRequest;
    type Response = CompleteResponse;
    type DomainError = CompleteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != COMPLETE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<FederatedRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).complete(context, request)
    }
}

#[derive(Debug)]
pub struct FederatedStart;
impl RequestCapability for FederatedStart {
    type Request = StartRequest;
    type Response = StartResponse;
    type DomainError = StartError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != START_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<FederatedRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).start(context, request)
    }
}

impl serde::Serialize for CompleteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::InvalidCallback => serializer.serialize_str("invalid_callback"),
            Self::InvalidState => serializer.serialize_str("invalid_state"),
            Self::ProviderRejected => serializer.serialize_str("provider_rejected"),
            Self::UnverifiedIdentity => serializer.serialize_str("unverified_identity"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CompleteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "invalid_callback" => Ok(Self::InvalidCallback),
                "invalid_state" => Ok(Self::InvalidState),
                "provider_rejected" => Ok(Self::ProviderRejected),
                "unverified_identity" => Ok(Self::UnverifiedIdentity),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for StartError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidReturnTo => serializer.serialize_str("invalid_return_to"),
            Self::ProviderUnavailable => serializer.serialize_str("provider_unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for StartError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_return_to" => Ok(Self::InvalidReturnTo),
                "provider_unavailable" => Ok(Self::ProviderUnavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_complete_request(value: &CompleteRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_request(wire: &str) -> Result<CompleteRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_response(value: &CompleteResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_response(wire: &str) -> Result<CompleteResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_error(value: &CompleteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_error(wire: &str) -> Result<CompleteError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_start_request(value: &StartRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_request(wire: &str) -> Result<StartRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_start_response(value: &StartResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_response(wire: &str) -> Result<StartResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_start_error(value: &StartError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_start_error(wire: &str) -> Result<StartError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoFederatedCompleteResult {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure>;
}
impl __LensoIntoFederatedCompleteResult for Result<CompleteResponse, CompleteError> {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoFederatedCompleteResult for Result<CompleteResponse, lenso_module_authoring::ModuleError<CompleteError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_module_authoring::ModuleError::Domain(error)) => Ok(Err(error)),
            Err(lenso_module_authoring::ModuleError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoFederatedCompleteResult for Result<CompleteResponse, FederatedCompleteInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(FederatedCompleteInvocationError::Domain(error)) => Ok(Err(error)),
            Err(FederatedCompleteInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoFederatedStartResult {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure>;
}
impl __LensoIntoFederatedStartResult for Result<StartResponse, StartError> {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoFederatedStartResult for Result<StartResponse, lenso_module_authoring::ModuleError<StartError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_module_authoring::ModuleError::Domain(error)) => Ok(Err(error)),
            Err(lenso_module_authoring::ModuleError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoFederatedStartResult for Result<StartResponse, FederatedStartInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<StartResponse, StartError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(FederatedStartInvocationError::Domain(error)) => Ok(Err(error)),
            Err(FederatedStartInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait FederatedProvider: fmt::Debug + 'static {
    fn complete(&self, context: InvocationContext, request: CompleteRequest) -> NativeRequestFuture<FederatedComplete>;
    fn start(&self, context: InvocationContext, request: StartRequest) -> NativeRequestFuture<FederatedStart>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_federated {
    ($module:ty, $support:path) => {
        use $support as __LensoNativeSupportFederated;
        impl $crate::FederatedProvider for $module {
        fn complete(&self, context: __LensoNativeSupportFederated::InvocationContext, request: $crate::CompleteRequest) -> __LensoNativeSupportFederated::NativeRequestFuture<$crate::FederatedComplete> {
            let module = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$module>::complete(&module, context, request).await;
                $crate::__LensoIntoFederatedCompleteResult::__lenso_into_result(result)
            })
        }
        fn start(&self, context: __LensoNativeSupportFederated::InvocationContext, request: $crate::StartRequest) -> __LensoNativeSupportFederated::NativeRequestFuture<$crate::FederatedStart> {
            let module = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$module>::start(&module, context, request).await;
                $crate::__LensoIntoFederatedStartResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct FederatedRequestEndpoint { provider: Rc<dyn FederatedProvider> }

#[derive(Debug)]
pub struct FederatedEndpoint<P: FederatedProvider> { provider: Rc<P>, request_endpoint: FederatedRequestEndpoint }
impl<P: FederatedProvider> FederatedEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn FederatedProvider> = provider.clone();
        Self { provider, request_endpoint: FederatedRequestEndpoint { provider: request_provider } }
    }
}

impl<P: FederatedProvider> NativeRequestEndpoint for FederatedEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        COMPLETE_OPERATION,
        START_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            COMPLETE_OPERATION => {
                let Ok(request) = request.downcast::<CompleteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).complete(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            START_OPERATION => {
                let Ok(request) = request.downcast::<StartRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).start(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_federated {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::FederatedEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_federated {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_federated!($provider, $support);
        __LensoNativeSupport::NativeModuleInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct FederatedClient {
    complete: NativeRequestHandle<FederatedComplete>,
    start: NativeRequestHandle<FederatedStart>,
}
impl FederatedClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn complete(&self, request: CompleteRequest) -> Result<CompleteResponse, FederatedCompleteInvocationError> {
        self.complete.invoke(COMPLETE_OPERATION, request).await
            .map_err(FederatedCompleteInvocationError::Runtime)?
            .map_err(FederatedCompleteInvocationError::Domain)
    }

    pub async fn complete_with_context(&self, context: InvocationContext, request: CompleteRequest) -> Result<CompleteResponse, FederatedCompleteInvocationError> {
        self.complete.invoke_with_context(COMPLETE_OPERATION, context, request).await
            .map_err(FederatedCompleteInvocationError::Runtime)?
            .map_err(FederatedCompleteInvocationError::Domain)
    }

    pub async fn start(&self, request: StartRequest) -> Result<StartResponse, FederatedStartInvocationError> {
        self.start.invoke(START_OPERATION, request).await
            .map_err(FederatedStartInvocationError::Runtime)?
            .map_err(FederatedStartInvocationError::Domain)
    }

    pub async fn start_with_context(&self, context: InvocationContext, request: StartRequest) -> Result<StartResponse, FederatedStartInvocationError> {
        self.start.invoke_with_context(START_OPERATION, context, request).await
            .map_err(FederatedStartInvocationError::Runtime)?
            .map_err(FederatedStartInvocationError::Domain)
    }
}

impl CapabilityClient for FederatedClient {
    type Dependencies = ModuleDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            complete: dependencies.one::<FederatedComplete>()?,
            start: dependencies.one::<FederatedStart>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::ModuleFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum FederatedCompleteInvocationError {
    Domain(CompleteError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum FederatedStartInvocationError {
    Domain(StartError),
    Runtime(RuntimeFailure),
}
