// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

use lenso_module_authoring::CapabilityClient;
pub const CAPABILITY_ID: &str = "lenso.auth.credential-issuer@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const CREDENTIAL_ISSUER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const CREDENTIAL_ISSUER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_credential_issuer { () => { "{\"capability_id\":\"lenso.auth.credential-issuer@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"issue\",\"revoke\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_credential_issuer_client { () => { "{\"capability_id\":\"lenso.auth.credential-issuer@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

pub const ISSUE_OPERATION: &str = "issue";
pub const REVOKE_OPERATION: &str = "revoke";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IssueRequest {
    #[serde(rename = "actor_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_kind: String,
    #[serde(rename = "assurance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assurance: String,
    #[serde(rename = "audience")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub audience: Vec<String>,
    #[serde(rename = "claims")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub claims: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct IssueResponse {
    #[serde(rename = "credential")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub credential: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

impl fmt::Debug for IssueResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("IssueResponse")
            .field("credential", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("session_id", &self.session_id)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum IssueError {
    Disabled,
    Expired,
    InvalidAuthority,
    InvalidSubject,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeRequest {
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RevokeError {
    InvalidSession,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct CredentialIssuerIssue;
impl RequestCapability for CredentialIssuerIssue {
    type Request = IssueRequest;
    type Response = IssueResponse;
    type DomainError = IssueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ISSUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CredentialIssuerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).issue(context, request)
    }
}

#[derive(Debug)]
pub struct CredentialIssuerRevoke;
impl RequestCapability for CredentialIssuerRevoke {
    type Request = RevokeRequest;
    type Response = RevokeResponse;
    type DomainError = RevokeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REVOKE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<CredentialIssuerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).revoke(context, request)
    }
}

impl serde::Serialize for IssueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Disabled => serializer.serialize_str("disabled"),
            Self::Expired => serializer.serialize_str("expired"),
            Self::InvalidAuthority => serializer.serialize_str("invalid_authority"),
            Self::InvalidSubject => serializer.serialize_str("invalid_subject"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for IssueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "disabled" => Ok(Self::Disabled),
                "expired" => Ok(Self::Expired),
                "invalid_authority" => Ok(Self::InvalidAuthority),
                "invalid_subject" => Ok(Self::InvalidSubject),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RevokeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidSession => serializer.serialize_str("invalid_session"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RevokeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_session" => Ok(Self::InvalidSession),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_issue_request(value: &IssueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_issue_request(wire: &str) -> Result<IssueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_issue_response(value: &IssueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_issue_response(wire: &str) -> Result<IssueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_issue_error(value: &IssueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_issue_error(wire: &str) -> Result<IssueError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_revoke_request(value: &RevokeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_request(wire: &str) -> Result<RevokeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_response(value: &RevokeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_response(wire: &str) -> Result<RevokeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_error(value: &RevokeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_error(wire: &str) -> Result<RevokeError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoCredentialIssuerIssueResult {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure>;
}
impl __LensoIntoCredentialIssuerIssueResult for Result<IssueResponse, IssueError> {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCredentialIssuerIssueResult for Result<IssueResponse, lenso_module_authoring::ModuleError<IssueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_module_authoring::ModuleError::Domain(error)) => Ok(Err(error)),
            Err(lenso_module_authoring::ModuleError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCredentialIssuerIssueResult for Result<IssueResponse, CredentialIssuerIssueInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<IssueResponse, IssueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CredentialIssuerIssueInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CredentialIssuerIssueInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoCredentialIssuerRevokeResult {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure>;
}
impl __LensoIntoCredentialIssuerRevokeResult for Result<RevokeResponse, RevokeError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoCredentialIssuerRevokeResult for Result<RevokeResponse, lenso_module_authoring::ModuleError<RevokeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_module_authoring::ModuleError::Domain(error)) => Ok(Err(error)),
            Err(lenso_module_authoring::ModuleError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoCredentialIssuerRevokeResult for Result<RevokeResponse, CredentialIssuerRevokeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeResponse, RevokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(CredentialIssuerRevokeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(CredentialIssuerRevokeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait CredentialIssuerProvider: fmt::Debug + 'static {
    fn issue(&self, context: InvocationContext, request: IssueRequest) -> NativeRequestFuture<CredentialIssuerIssue>;
    fn revoke(&self, context: InvocationContext, request: RevokeRequest) -> NativeRequestFuture<CredentialIssuerRevoke>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_credential_issuer {
    ($module:ty, $support:path) => {
        use $support as __LensoNativeSupportCredentialIssuer;
        impl $crate::CredentialIssuerProvider for $module {
        fn issue(&self, context: __LensoNativeSupportCredentialIssuer::InvocationContext, request: $crate::IssueRequest) -> __LensoNativeSupportCredentialIssuer::NativeRequestFuture<$crate::CredentialIssuerIssue> {
            let module = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$module>::issue(&module, context, request).await;
                $crate::__LensoIntoCredentialIssuerIssueResult::__lenso_into_result(result)
            })
        }
        fn revoke(&self, context: __LensoNativeSupportCredentialIssuer::InvocationContext, request: $crate::RevokeRequest) -> __LensoNativeSupportCredentialIssuer::NativeRequestFuture<$crate::CredentialIssuerRevoke> {
            let module = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$module>::revoke(&module, context, request).await;
                $crate::__LensoIntoCredentialIssuerRevokeResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct CredentialIssuerRequestEndpoint { provider: Rc<dyn CredentialIssuerProvider> }

#[derive(Debug)]
pub struct CredentialIssuerEndpoint<P: CredentialIssuerProvider> { provider: Rc<P>, request_endpoint: CredentialIssuerRequestEndpoint }
impl<P: CredentialIssuerProvider> CredentialIssuerEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn CredentialIssuerProvider> = provider.clone();
        Self { provider, request_endpoint: CredentialIssuerRequestEndpoint { provider: request_provider } }
    }
}

impl<P: CredentialIssuerProvider> NativeRequestEndpoint for CredentialIssuerEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ISSUE_OPERATION,
        REVOKE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ISSUE_OPERATION => {
                let Ok(request) = request.downcast::<IssueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).issue(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REVOKE_OPERATION => {
                let Ok(request) = request.downcast::<RevokeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).revoke(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_credential_issuer {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::CredentialIssuerEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_credential_issuer {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_credential_issuer!($provider, $support);
        __LensoNativeSupport::NativeModuleInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct CredentialIssuerClient {
    issue: NativeRequestHandle<CredentialIssuerIssue>,
    revoke: NativeRequestHandle<CredentialIssuerRevoke>,
}
impl CredentialIssuerClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn issue(&self, request: IssueRequest) -> Result<IssueResponse, CredentialIssuerIssueInvocationError> {
        self.issue.invoke(ISSUE_OPERATION, request).await
            .map_err(CredentialIssuerIssueInvocationError::Runtime)?
            .map_err(CredentialIssuerIssueInvocationError::Domain)
    }

    pub async fn issue_with_context(&self, context: InvocationContext, request: IssueRequest) -> Result<IssueResponse, CredentialIssuerIssueInvocationError> {
        self.issue.invoke_with_context(ISSUE_OPERATION, context, request).await
            .map_err(CredentialIssuerIssueInvocationError::Runtime)?
            .map_err(CredentialIssuerIssueInvocationError::Domain)
    }

    pub async fn revoke(&self, request: RevokeRequest) -> Result<RevokeResponse, CredentialIssuerRevokeInvocationError> {
        self.revoke.invoke(REVOKE_OPERATION, request).await
            .map_err(CredentialIssuerRevokeInvocationError::Runtime)?
            .map_err(CredentialIssuerRevokeInvocationError::Domain)
    }

    pub async fn revoke_with_context(&self, context: InvocationContext, request: RevokeRequest) -> Result<RevokeResponse, CredentialIssuerRevokeInvocationError> {
        self.revoke.invoke_with_context(REVOKE_OPERATION, context, request).await
            .map_err(CredentialIssuerRevokeInvocationError::Runtime)?
            .map_err(CredentialIssuerRevokeInvocationError::Domain)
    }
}

impl CapabilityClient for CredentialIssuerClient {
    type Dependencies = ModuleDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            issue: dependencies.one::<CredentialIssuerIssue>()?,
            revoke: dependencies.one::<CredentialIssuerRevoke>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::ModuleFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CredentialIssuerIssueInvocationError {
    Domain(IssueError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum CredentialIssuerRevokeInvocationError {
    Domain(RevokeError),
    Runtime(RuntimeFailure),
}
